services:
  - type: web
    name: mi-mobile-indicator-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: mi_mobile_indicator
      - key: JWT_SECRET_KEY
        value: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6
      - key: STRIPE_API_KEY
        value: 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
      - key: TWELVE_DATA_API_KEY
        value: fade197d6af1440ba7cb285ebeed3306
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: mimobileindicator@gmail.com
      - key: SMTP_PASSWORD
        value: MImobileindicor@1
      - key: SENDER_EMAIL
        value: mimobileindicator@gmail.com
      - key: MARKETAUX_API_KEY
        value: OEFGTIfdJUTFSiamPg4kaY4VXtuViV3gBULDwzLW
